/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULA_H_RPCGEN
#define _CALCULA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	int x;
	int y;
};
typedef struct operandos operandos;

#define PROG 55555555
#define VERSAO 101

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 2
extern  int * add_101(operandos *, CLIENT *);
extern  int * add_101_svc(operandos *, struct svc_req *);
#define SUB 3
extern  int * sub_101(operandos *, CLIENT *);
extern  int * sub_101_svc(operandos *, struct svc_req *);
extern int prog_101_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 2
extern  int * add_101();
extern  int * add_101_svc();
#define SUB 3
extern  int * sub_101();
extern  int * sub_101_svc();
extern int prog_101_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULA_H_RPCGEN */
