/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULA_H_RPCGEN
#define _CALCULA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	int x;
	int y;
};
typedef struct operandos operandos;

#define PROG 55555555
#define VERSAO 102

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_102(operandos *, CLIENT *);
extern  int * add_102_svc(operandos *, struct svc_req *);
#define SUB 2
extern  int * sub_102(operandos *, CLIENT *);
extern  int * sub_102_svc(operandos *, struct svc_req *);
#define MULT 3
extern  int * mult_102(operandos *, CLIENT *);
extern  int * mult_102_svc(operandos *, struct svc_req *);
#define DIVI 4
extern  int * divi_102(operandos *, CLIENT *);
extern  int * divi_102_svc(operandos *, struct svc_req *);
extern int prog_102_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_102();
extern  int * add_102_svc();
#define SUB 2
extern  int * sub_102();
extern  int * sub_102_svc();
#define MULT 3
extern  int * mult_102();
extern  int * mult_102_svc();
#define DIVI 4
extern  int * divi_102();
extern  int * divi_102_svc();
extern int prog_102_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULA_H_RPCGEN */
