/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int * add_102_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

        printf("Requisicao de adicao para %d e %d\n", argp->x, argp->y);
        result = argp->x + argp->y;

	return &result;
}

int * sub_102_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

        printf("Requisicao de subtracao para %d e %d\n", argp->x, argp->y);
        result = argp->x - argp->y;

	return &result;
}

int * mult_102_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	if(argp->x != 0 && argp->y !=0) {
        	printf("Requisicao de multiplicacao para %d e %d\n", argp->x, argp->y);
	        result = argp->x * argp->y;
	} else {
		printf("Valor 0 inválido.");
	}
	return &result;
}

int * divi_102_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;

	if(argp->x != 0 && argp->y !=0) {
        	printf("Requisicao de divisao para %d e %d\n", argp->x, argp->y);
	        result = argp->x / argp->y;
	} else {
		printf("Valor 0 inválido.");
	}

	return &result;
}
