/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fibonacci.h"
#include <stdio.h>

int fib( CLIENT *clnt, int x) {
        operandos ops;
        int *result;

        ops.x = x;
        /* Chama o stub cliente criado pelo rpcgen */
        result = fib_105(&ops,clnt);
        if (result==NULL) {
                fprintf(stderr,"Problema na chamada RPC\n");
                exit(0); }
        return(*result);
} /* fim função add local */


int main( int argc, char *argv[]) {
        CLIENT *clnt;
        int x;

        if (argc!=3) {
                fprintf(stderr,"Uso: %s hostname num1 \n",argv[0]);
                exit(0); }
        clnt = clnt_create(argv[1], PROG, VERSAO, "udp");
        /* Garantindo a criacao da ligacao com o remoto */
        if (clnt == (CLIENT *) NULL) {
                clnt_pcreateerror(argv[1]);
                exit(1); }
        /* Recupera os 2 operandos passados como argumento */
        x = atoi(argv[2]);
        printf("Resultado: %d \n", fib(clnt,x));
        return(0);
} /* fim main */

