/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FIBONACCI_H_RPCGEN
#define _FIBONACCI_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operandos {
	int x;
};
typedef struct operandos operandos;

#define PROG 55555555
#define VERSAO 105

#if defined(__STDC__) || defined(__cplusplus)
#define FIB 1
extern  int * fib_105(operandos *, CLIENT *);
extern  int * fib_105_svc(operandos *, struct svc_req *);
extern int prog_105_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FIB 1
extern  int * fib_105();
extern  int * fib_105_svc();
extern int prog_105_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operandos (XDR *, operandos*);

#else /* K&R C */
extern bool_t xdr_operandos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FIBONACCI_H_RPCGEN */
