/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fibonacci.h"

int *
fib_105_svc(operandos *argp, struct svc_req *rqstp)
{
	static int  result;
	int b=1, a=1, aux=0;
        printf("Requisicao de fibonacci para %d \n", argp->x);

	for(int i=0;i<argp->x;i++) {
 		aux = a + b;
		a = b;
		b = aux;
	}

        result = b;


	return &result;
}
