#!/usr/bin/env python3

import os
from sys import argv, stderr, path

PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_PATH = os.path.join(PATH, 'src')
path.append(SRC_PATH)

BINS_PATH = os.path.join(PATH, 'bins')

from functions import(
    build_keymap_dict,
    substitute_keys,
    write_result,
    get_scancodes
)

with open(argv[1]) as file:
    key_map = file.readlines()
    key_map = [line.strip() for line in key_map][1:]

key_dict = build_keymap_dict(key_map)

scancodes = get_scancodes(argv[2])
scancodes = scancodes.split('\n')

translated_data = substitute_keys(key_dict, scancodes)
translated_data = ''.join(translated_data)

write_result(translated_data)

print('Translation completed!!!')
